import{a as S,S as b,i as s}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",v="54337212-655e7339b0825c0fa1c24fc71";async function f(o,t){return(await S.get(q,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new b(".gallery a");function y(o){const t=o.map(n=>`
      <li class="gallery-item">
        <a href="${n.largeImageURL}">
          <img
            src="${n.webformatURL}"
            alt="${n.tags}"
            loading="lazy"
          />
        </a>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){g.innerHTML=""}function p(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function M(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const P=document.querySelector(".form"),O=document.querySelector(".load-more");let a="",i=1;const w=15;let c=0;P.addEventListener("submit",x);O.addEventListener("click",E);async function x(o){if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),!a){s.warning({message:"Please enter a search query!",position:"topRight"});return}i=1,c=0,B(),d(),p();try{const t=await f(a,i),n=t.hits;if(c=t.totalHits,n.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(n),i*w>=c?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M()}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}}async function E(){i+=1,p();try{const t=(await f(a,i)).hits;y(t),T(),i*w>=c&&(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}}function T(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
